### ISSUE TITLE
Assigning cards

### ISSUE THREAD

**Issue by droidsb** [droidsb/General-Coding#15]
How do I assign a number from the array to the card?

**Comment by fosterbrereton** [comment]
you mean something like:

```
var card = myDeck[i];
```

Note that this is a copy, so the card will still be in the deck. In order to fix that, you can `pop` an element off the back of the array (the opposite of a `push`):

```
var card = myDeck.pop();
```

Though it may not be a problem immediately, at some point you will need to make sure myDeck has at least a card in it before popping.
